### ISSUE TITLE
Recommends a champion to pick but not to pick

### ISSUE THREAD

**Issue by Vianpyro** [Piaero/what2pick#16]
Hello,

I think I just found an issue:
I was testing some compositions, including the one shown in the picture below: am I supposed to play Udyr or not? 😆 
![opp](https://user-images.githubusercontent.com/10519369/103464273-63860b80-4d00-11eb-8615-018d14636871.png)

**Comment by Piaero** [comment]
Thank you for your report :) I knew such contradictory propositions could happen but couldn't find a way to reproduce it :) Few days ago I have made a TODO task "Remove "Avoid To Pick" from "Suggested" champions" so the issue will be repaired in the future :) 
Anyway it's funny that some tutorials claim Udyr is countering Graves, and other tutorials say otherwise: that Graves is countering Udyr :D 
Kind regards and I am thankful for your comment :)

**Comment by Piaero** [comment]
Fixed with commit 98aea825718c1247c044f83a2f833e3b3e8efa45
Thank you for your report :)
